### ISSUE TITLE
Remove RFN

### ISSUE THREAD

**Issue by davelab6** [phoikoi/VT323#1]
https://github.com/phoikoi/VT323/blob/master/LICENSE.TXT#L2 has an RFN

A reserved font name isn't a good idea for 2 reasons.
1. It makes the process of collaboration via github cumbersome; if a
   memberof the general public clicks the 'fork' button up top right, they
   must either seek permission from you before-hand to use the RFN, or to
   immediately change the font name in the files as part of their first
   modification, and then you'll have to change it back.
2. Many websites who self host the font files will modify them, doing
   subsetting and format conversion, which are both explicitly defined in the
   OFL as kinds of modification subject to the RFN restriction. SIL have been
   willing to offer their view that the most popular web font formats are not
   format conversions subject to the RFN restriction, but popular web font
   bundling service Font Squirrel includes the less popular formats too, which
   do. And subsetting remains. So, changing the name or contacting you are
   both administrative burdens for these downstream users, and if they do
   contact you, for you; and many people won't think carefully about this and
   will just do so without asking, which formally terminates their license.
   Putting them in that position is not a good situation.

So not having any RFNs is my best recommendation. To do this, just remove that line. Note that only @phoikoi can do this :)

**Comment by phoikoi** [comment]
What is the purpose of the RFN?  is it a remnant of the past?  At the time I made the file (2011) it seemed to be the recommended practice, but things seem to have changed...?

**Comment by phoikoi** [comment]
RFN has been removed.

**Comment by davelab6** [comment]
Sil recommended it but I think its unwise for the reasons I've laid out.
Thanks!
