### ISSUE TITLE
Redraw everything with components

### ISSUE THREAD

**Issue by davelab6** [phoikoi/VT323#2]
> Python then drew the proper pixels into a 1:1 pixel grid as a monochrome PNG, which FontForge autoscanned into outlines.

Since the outlines are indeed created by an "autotraced scan" process, the technical and visual quality of the font can be improved, by re-engineering each glyph to be constructing using a dot component - this will result in a really small filesize, and a cleaner and uniform look in display usage.

**Comment by Fonthausen** [comment]
Good idea ! I will have a look at it and rebuild the font. It might even solve a lot of other issues.

**Comment by Fonthausen** [comment]
Peter,
are there any glyphs you would do different now ? Tomorrow I will build up again your typeface by using a pixel component to make every sharp and clear.

**Comment by phoikoi** [comment]
I've attached a screenshot of Fontforge showing the glyphs that have bothered me the most.  In particular, the comma, semicolon, and uppercase Q just seem rather ungainly and awkward, and the curly braces could use a little shaping with maybe some more... "serifs"? on the ends.  Basically my hangup is the extra pixels hanging off the glyphs.  At the time I was trying to be as faithful as possible to the original VT320 glyphs so I left them as they were.  But now, they can safely be reeducated.  Let me know if you have other ideas to improve them; I'm certainly not a veteran type designer, just a text terminal enthusiast.  :)
![screen shot 2016-07-04 at 21 12 42](https://cloud.githubusercontent.com/assets/1757216/16573801/ccfc66b0-422c-11e6-9b1e-794b82109896.jpg)

**Comment by Fonthausen** [comment]
That is awesome !

I have indeed encountered some things that I would have done differently. I will correct the ones you have marked.

In the glyph file I will mark the altered (and new) glyphs.

Peter,
do you need the mathematical borders ?

**Comment by phoikoi** [comment]
Not sure what you mean by mathematical borders?  Also, please leave a new comment; I don't get notified if an older comment is edited with new text.  :)

**Comment by Fonthausen** [comment]
At the bottom of your screenshot to the right, you can see them.

**Comment by davelab6** [comment]
These are 'box drawing' characters, check out https://github.com/adobe-type-tools/box-drawing

**Comment by davelab6** [comment]
Maybe @phoikoi could use the adobe software to recreate the boxes with the component @Fonthausen is using?

**Comment by Fonthausen** [comment]
That would be a great help !

**Comment by davelab6** [comment]
I think you can leave those glyphs alone, and we can consider upgrading them in the future

**Comment by Fonthausen** [comment]
Fine by me. :)

**Comment by Fonthausen** [comment]
I uploaded the new VT323 to be reviewed on my GitHub: https://github.com/Fonthausen/VT323_GFPlus.

Nhung can have a look at the Vietnamese. I built the combined vietnamese accents, but maybe we could use Glyphs' automated brevecomb_acutecomb (etc.) possibilities. I put this question on Alexei's Git.

**Comment by phoikoi** [comment]
I don't have Glyphs, only FontLab and FontForge. Is it possible to make a UFO version which FontForge can open?

**Comment by davelab6** [comment]
Jacques, please do fork this repo so that your changes can be merged back -
please see https://guides.github.com/activities/forking/ and
https://help.github.com/articles/fork-a-repo/ :)

Peter, commit one now

**Comment by davelab6** [comment]
Peter, please see https://github.com/phoikoi/VT323/pull/3

**Comment by phoikoi** [comment]
Cool, thanks.

**Comment by phoikoi** [comment]
Hm, Fontforge apparently doesn't play well with this UFO file... am I doing something wrong?  Wish I could test with FontLab too but it apparently doesn't know about UFO.
![screen shot 2016-07-05 at 17 12 33](https://cloud.githubusercontent.com/assets/1757216/16603810/064f8eae-42d4-11e6-9e15-01ef4d923d37.jpg)

**Comment by davelab6** [comment]
Glyphs has a 30 day full free trial, I suggest using that :)

**Comment by phoikoi** [comment]
I'd really like to have the master version of the font in an open-source format that can produce the output from an open-source tool.  Is this possible?

**Comment by davelab6** [comment]
Yes, glyphs is an open format and fontmake is a libre licensed tool that
can build it.

**Comment by phoikoi** [comment]
cool. just checking.

**Comment by davelab6** [comment]
If you would be interested to make a Makefile (or setup.py) that build the
binaries from the .glyphs file using fontmake that would be awesome :D

**Comment by phoikoi** [comment]
hm, the output from fontmake looks pretty much the same as the output from FontForge (when using the glyphs file as input: `fontmake -g VT323.glyphs -o ttf`.)  When using the VT323-Regular UFO as input (specifying TTF output), fontmake crashed:

``` bash
$ fontmake -u VT323-Regular.ufo -o ttf

>> Building TTFs
>> Removing overlaps for VT323-Regular
>> Converting curves for VT323-Regular
New spline lengths:
3: 4
4: 4

Traceback (most recent call last):
  File "/Users/peter/.pyenv/versions/fonts/bin/fontmake", line 9, in <module>
    load_entry_point('fontmake', 'console_scripts', 'fontmake')()
  File "/Users/peter/dev/fonts/fontmake/Lib/fontmake/__main__.py", line 63, in main
    project.run_from_ufos(ufo_paths, **args)
  File "/Users/peter/dev/fonts/fontmake/Lib/fontmake/font_project.py", line 296, in run_from_ufos
    self.build_ttfs(ufos, mti_paths=mti_paths, **kwargs)
  File "/Users/peter/dev/fonts/fontmake/Lib/fontmake/font_project.py", line 157, in build_ttfs
    self.save_otfs(ufos, ttf=True, **kwargs)
  File "/Users/peter/.pyenv/versions/2.7.11/envs/fonts/lib/python2.7/site-packages/FontTools/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
TypeError: save_otfs() got an unexpected keyword argument 'family_name'
```

**Comment by davelab6** [comment]
Nice. Please file bugs upstream.

Something is definitely not right with the UFO, when I open it in Glyphs it
is also messed up.

**Comment by davelab6** [comment]
>  FontLab too but it apparently doesn't know about UFO.

It does, using RoboFab

**Comment by davelab6** [comment]
I filed https://forum.glyphsapp.com/t/ufo-export-not-working-with-many-components/4706 to see if Glyphs community can help shed light on this.

**Comment by davelab6** [comment]
> I'd really like to have the master version of the font in an open-source format that can produce the output from an open-source tool. Is this possible?

So, to answer that question, it seems today, no, because of practical issues in fontmake, but in the future it should work out that way. 

Basically my position today is that Fontforge is okay for hobbyists and libre licensing purists but after delivering dozens of type design workshops for beginners in cities around the world, almost none of the people I taught FontForge to are still using it; almost everyone is using Glyphs. So for promoting free culture and remixing and collaboration, Fontforge is not helpful, and using Glyphs is. Later this year TruFont will mature and will read and write the Glyphs format, and it will eventually be a useful replacement for FontForge in its current position - TruFont is currently just a toy and not useful for any real work even by beginners - and perhaps in 10 years it will have become the main editor everyone is using. But I doubt it.

**Comment by phoikoi** [comment]
Yeah, it's a complex domain... to create a tool for designers to use requires both deep knowledge of type design and of good software development.  It's the rare person that has that combination.  In my case, I used FontForge because it had (has) the python module that allows it to be scripted from outside the app.  Without that I never would have made VT323 (and other later efforts), so I'm quite grateful it was around.
So... in that spirit, I would like for there to be a FontForge-compatible version of the UFO in this repo alongside the standard one, if that is at all possible--perhaps a decomposed version, with the components realized into regular paths within the glyphs?  The GF version would of course be the highly optimized one, but if I could request for that one thing to be added in when the new GF version is ready to be tagged and released, it would be most appreciated.  I wouldn't expect anybody to maintain that version beyond making a new version to track any new GF versions, if any.  If my trial version of Glyphs is still working when the release is ready, I'd be happy to make it myself, but if not, could somebody drop one?

**Comment by davelab6** [comment]
Why not just open the TTF in FontForge?

**Comment by phoikoi** [comment]
True... not sure if it would have a seizure with the components though...?

**Comment by phoikoi** [comment]
One other thing... are the powerline glyphs legal for inclusion? (0xE0A0 - 0xE0A2, 0xE0B0 - 0xE0B3)  That would be cool to have, no, especially for a terminal-style fixed-pitch typeface?

**Comment by davelab6** [comment]
The TTF preview seems OK in finder:

<img width="193" alt="screen shot 2016-07-05 at 23 10 37" src="https://cloud.githubusercontent.com/assets/261579/16606439/03d0edc6-4306-11e6-8305-23728830e0f5.png">

The file in fontforge doesn't show any components:

![screen shot 2016-07-05 at 23 11 34](https://cloud.githubusercontent.com/assets/261579/16606440/03d16300-4306-11e6-95c0-bac5127e50fc.png)

But the file in Glyphs does:

<img width="1440" alt="screen shot 2016-07-05 at 23 12 41" src="https://cloud.githubusercontent.com/assets/261579/16606441/03d19528-4306-11e6-86dc-6060dfa04eff.png">

However, when I check the file with ttx, I see that it is full of contours. Hmm. Well, the regularity means they file will compress well, but still, this seems unexpected to me. I'll follow up on the glyphs forum about it. 

Meanwhile I added a TTF and put the versions into folders and made a new PR.

**Comment by davelab6** [comment]
Powerline characters are super niche for the web; Google Fonts removes them from its subsets so its out of scope for Jacques, I think... but if you'd like to add them that would be awesome! :) No pressure of course

**Comment by phoikoi** [comment]
I'm not sure how he went about creating the new glyphs, so I don't know if my efforts would be completely compatible, but I can try while my trial copy is functional.  :)

**Comment by phoikoi** [comment]
So is the version I just merged the final v2.0 or is there more work in progress?  I'll tag it if it's the final version.

**Comment by Fonthausen** [comment]
The file was made in the cutting edge version of Glyphs using smart components. I do not if the standard version is able to work with them. The file contains two smart components. 

Would it be a help, if I add one or more "normal" components for you to work with the powerline glyphs ?

**Comment by Fonthausen** [comment]
I forked the RP and reviewed the files. I added (automatic) features and some minor fixes. In the RP you will find a decomposed version with a VFB an UFO. Decomposed version is for review purposes only.

**Comment by davelab6** [comment]
> So is the version I just merged the final v2.0 or is there more work in progress? I'll tag it if it's the final version.

Its just WIP

**Comment by davelab6** [comment]
> I can try while my trial copy is functional. :)

Maybe I can arrange to sponsor your license fee if you would like that

**Comment by davelab6** [comment]
https://github.com/Fonthausen/VT323 looks good; you can write over the top of my v2.0 folder btw :)

**Comment by davelab6** [comment]
OK :) Georg said,

> The distortion in the .ufo is caused by the smart components. They are not supposed in .ufo.
> 
> On export, if a component points to a none exporting glyph, it will be decomposed. And if it is a smart component, it will be decomposed. Both cases apply here.

So, in order to realise the filesize gain of using components, Jacques will need to pick which 'instances' of the smart component he has used, and 'decompose' them into their own glyphs as regular components, and mark those as exporting glyphs; then replace each smart component with its corresponding regular component. This will then ensure that when exporting a TTF. the regular components are exported and not converted to outlines, reducing the filesize substantially (and better than what woff2 can do, I expect) and also mean that the UFO export will work reliably. 

However, that will be a lot of work, and it seems like something a script can do. 

I think Jacques should not spend time on this by hand, but we could release a v2 with .glyphs sources and rely on woff2 compression to get the filesize down (since the smart component's decomposed outlines are very regular, unlike the v1.0 which because it was autotraced had very irregular outlines) and suggest FontForge users to edit the TTF, and propose a v3 that has the powerline/etc glyphs, regular components, UFO sources, etc.

**Comment by Fonthausen** [comment]
I had a talk with Kalapi this morning to solve this question. That is why I added the decomposed version. 

Kalapi had his doubt if using components would really have a lot of effect on file size.

**Comment by davelab6** [comment]
Yeah, possibly not with woff2 compression.

**Comment by Fonthausen** [comment]
Dave,

> https://github.com/Fonthausen/VT323 looks good; you can write over the top of my v2.0 folder btw :)

I will nest time, but I have to get used to GitHub and didn’t want to break stuff :)

**Comment by davelab6** [comment]
All good :)

**Comment by phoikoi** [comment]
> Maybe I can arrange to sponsor your license fee if you would like that

That would be awesome.  Thanks!

**Comment by Fonthausen** [comment]
Dave, I read your remark on the GlyphsApp forum. Do you want me to do dive into VT323 and dismantle all the smart components ?

**Comment by davelab6** [comment]
No, I think you should not spend time on this by hand, but we could release a v2 with .glyphs sources and rely on woff2 compression to get the filesize down :)

**Comment by phoikoi** [comment]
@davelab6 I guess I can tag a v2.0 github release now and close this issue? :grin:

**Comment by davelab6** [comment]
Yes, GF is serving Version 2.000 so please do :)

**Comment by phoikoi** [comment]
Version 2.0 tagged as commit 9bd4b3f.

**Comment by davelab6** [comment]
Thanks!
